# Generated by Django 3.2.8 on 2021-10-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        choices=[("BRL", "Real"), ("BRL", "Euro"), ("BRL", "Iene")], max_length=3
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
