name: Django Tests

on:
  push:
    branches: [main, backend]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db: [postgres]
        python-version: [3.9]
        include:
          - db: postgres
            db_user: runner
            db_password: ""

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres createuser -s runner
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install apprise braintree coverage coveralls
      - name: Run Tests
        env:
          DEBUG: False
          SECRET_KEY: fake
          VAT_COMPLY_URL: fake
          DB: ${{ matrix.db }}
          DB_HOST: 127.0.0.1
          DB_NAME: currency
          DB_USER: ${{ matrix.db_user }}
          DB_PASS: ${{ matrix.db_password }}
        run: |
          coverage run --source="." backend/manage.py test && coverage xml

      - name: Run codacy-coverage-reporter
        uses: slavcodev/coverage-monitor-action@1.2.0
        with:
          github_token: ${{ secrets.COVERAGE_SECRET }}
          clover_file: "coverage.xml"
          threshold_alert: 10
          threshold_warning: 50
